// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBly5qKzSP5SXQzKfxR0WCV-sM9_-vfZPM',
    appId: '1:959785563239:web:0e0cf529b664d76f61d0c2',
    messagingSenderId: '959785563239',
    projectId: 'energy-app-new',
    authDomain: 'energy-app-new.firebaseapp.com',
    storageBucket: 'energy-app-new.firebasestorage.app',
    measurementId: 'G-4QDFV66CTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi3SghrVClaYft-lfPA_J9uoXuTlo44Ys',
    appId: '1:959785563239:android:d42eb1834fd9b20b61d0c2',
    messagingSenderId: '959785563239',
    projectId: 'energy-app-new',
    storageBucket: 'energy-app-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6i2L1vgh92h5-lcHgdC8u6Hmb8AuHICw',
    appId: '1:959785563239:ios:42ee07271018f2e361d0c2',
    messagingSenderId: '959785563239',
    projectId: 'energy-app-new',
    storageBucket: 'energy-app-new.firebasestorage.app',
    iosBundleId: 'com.example.energyManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6i2L1vgh92h5-lcHgdC8u6Hmb8AuHICw',
    appId: '1:959785563239:ios:42ee07271018f2e361d0c2',
    messagingSenderId: '959785563239',
    projectId: 'energy-app-new',
    storageBucket: 'energy-app-new.firebasestorage.app',
    iosBundleId: 'com.example.energyManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBly5qKzSP5SXQzKfxR0WCV-sM9_-vfZPM',
    appId: '1:959785563239:web:39c81b0e750c268c61d0c2',
    messagingSenderId: '959785563239',
    projectId: 'energy-app-new',
    authDomain: 'energy-app-new.firebaseapp.com',
    storageBucket: 'energy-app-new.firebasestorage.app',
    measurementId: 'G-XZND2E0RPD',
  );

}